// Data referensi dropdown — hasil ekstraksi dari form APL.01 asli
// Digunakan di app/assesi/apl1/[event_id]/[assesi_id]/page.tsx

export const KOTA_DOMISILI_OPTIONS = [
  { value: "1", label: "Aceh Selatan" },
  { value: "2", label: "Aceh Tenggara" },
  { value: "3", label: "Aceh Timur" },
  { value: "4", label: "Aceh Tengah" },
  { value: "5", label: "Aceh Barat" },
  { value: "6", label: "Aceh Besar" },
  { value: "7", label: "Pidie" },
  { value: "8", label: "Aceh Utara" },
  { value: "9", label: "Simeulue" },
  { value: "10", label: "Aceh Singkil" },
  { value: "11", label: "Bireuen" },
  { value: "12", label: "Aceh Barat Daya" },
  { value: "13", label: "Gayo Lues" },
  { value: "14", label: "Aceh Jaya" },
  { value: "15", label: "Nagan Raya" },
  { value: "16", label: "Aceh Tamiang" },
  { value: "17", label: "Bener Meriah" },
  { value: "18", label: "Pidie Jaya" },
  { value: "19", label: "Kota Banda Aceh" },
  { value: "20", label: "Kota Sabang" },
  { value: "21", label: "Kota Lhokseumawe" },
  { value: "22", label: "Kota Langsa" },
  { value: "23", label: "Kota Subulussalam" },
  { value: "24", label: "Tapanuli Tengah" },
  { value: "25", label: "Tapanuli Utara" },
  { value: "26", label: "Tapanuli Selatan" },
  { value: "27", label: "Nias" },
  { value: "28", label: "Langkat" },
  { value: "29", label: "Karo" },
  { value: "30", label: "Deli Serdang" },
  { value: "31", label: "Simalungun" },
  { value: "32", label: "Asahan" },
  { value: "33", label: "Labuhanbatu" },
  { value: "34", label: "Dairi" },
  { value: "35", label: "Toba Samosir" },
  { value: "36", label: "Mandailing Natal" },
  { value: "37", label: "Nias Selatan" },
  { value: "38", label: "Pakpak Bharat" },
  { value: "39", label: "Humbang Hasundutan" },
  { value: "40", label: "Samosir" },
  { value: "41", label: "Serdang Bedagai" },
  { value: "42", label: "Batu Bara" },
  { value: "43", label: "Padang Lawas Utara" },
  { value: "44", label: "Padang Lawas" },
  { value: "45", label: "Labuhanbatu Selatan" },
  { value: "46", label: "Labuhanbatu Utara" },
  { value: "47", label: "Nias Utara" },
  { value: "48", label: "Nias Barat" },
  { value: "49", label: "Kota Medan" },
  { value: "50", label: "Kota Pematangsiantar" },
  { value: "51", label: "Kota Sibolga" },
  { value: "52", label: "Kota Tanjung Balai" },
  { value: "53", label: "Kota Binjai" },
  { value: "54", label: "Kota Tebing Tinggi" },
  { value: "55", label: "Kota Padang Sidempuan" },
  { value: "56", label: "Kota Gunung Sitoli" },
  { value: "57", label: "Pesisir Selatan" },
  { value: "58", label: "Solok" },
  { value: "59", label: "Sijunjung" },
  { value: "60", label: "Tanah Datar" },
  { value: "61", label: "Padang Pariaman" },
  { value: "62", label: "Agam" },
  { value: "63", label: "Lima Puluh Kota" },
  { value: "64", label: "Pasaman" },
  { value: "65", label: "Kepulauan Mentawai" },
  { value: "66", label: "Dharmasraya" },
  { value: "67", label: "Solok Selatan" },
  { value: "68", label: "Pasaman Barat" },
  { value: "69", label: "Kota Padang" },
  { value: "70", label: "Kota Solok" },
  { value: "71", label: "Kota Sawahlunto" },
  { value: "72", label: "Kota Padangpanjang" },
  { value: "73", label: "Kota Bukittinggi" },
  { value: "74", label: "Kota Payakumbuh" },
  { value: "75", label: "Kota Pariaman" },
  { value: "76", label: "Kampar" },
  { value: "77", label: "Indragiri Hulu" },
  { value: "78", label: "Bengkalis" },
  { value: "79", label: "Indragiri Hilir" },
  { value: "80", label: "Pelalawan" },
  { value: "81", label: "Rokan Hulu" },
  { value: "82", label: "Rokan Hilir" },
  { value: "83", label: "Siak" },
  { value: "84", label: "Kuantan Singingi" },
  { value: "85", label: "Kepulauan Meranti" },
  { value: "86", label: "Kota Pekanbaru" },
  { value: "87", label: "Kota Dumai" },
  { value: "88", label: "Kerinci" },
  { value: "89", label: "Merangin" },
  { value: "90", label: "Sarolangun" },
  { value: "91", label: "Batang Hari" },
  { value: "92", label: "Muaro Jambi" },
  { value: "93", label: "Tanjung Jabung Barat" },
  { value: "94", label: "Tanjung Jabung Timur" },
  { value: "95", label: "Bungo" },
  { value: "96", label: "Tebo" },
  { value: "97", label: "Kota Jambi" },
  { value: "98", label: "Kota Sungai Penuh" },
  { value: "99", label: "Ogan Komering Ulu" },
  { value: "100", label: "Ogan Komering Ilir" },
  { value: "101", label: "Muara Enim" },
  { value: "102", label: "Lahat" },
  { value: "103", label: "Musi Rawas" },
  { value: "104", label: "Musi Banyuasin" },
  { value: "105", label: "Banyuasin" },
  { value: "106", label: "Ogan Komering Ulu Timur" },
  { value: "107", label: "Ogan Komering Ulu Selatan" },
  { value: "108", label: "Ogan Ilir" },
  { value: "109", label: "Empat Lawang" },
  { value: "110", label: "Penukal Arab Lematang I" },
  { value: "111", label: "Musi Rawas Utara" },
  { value: "112", label: "Kota Palembang" },
  { value: "113", label: "Kota Pagar Alam" },
  { value: "114", label: "Kota Lubuklinggau" },
  { value: "115", label: "Kota Prabumulih" },
  { value: "116", label: "Bengkulu Selatan" },
  { value: "117", label: "Rejang Lebong" },
  { value: "118", label: "Bengkulu Utara" },
  { value: "119", label: "Kaur" },
  { value: "120", label: "Seluma" },
  { value: "121", label: "Mukomuko" },
  { value: "122", label: "Lebong" },
  { value: "123", label: "Kepahiang" },
  { value: "124", label: "Bengkulu Tengah" },
  { value: "125", label: "Kota Bengkulu" },
  { value: "126", label: "Lampung Selatan" },
  { value: "127", label: "Lampung Tengah" },
  { value: "128", label: "Lampung Utara" },
  { value: "129", label: "Lampung Barat" },
  { value: "130", label: "Tulang Bawang" },
  { value: "131", label: "Tanggamus" },
  { value: "132", label: "Lampung Timur" },
  { value: "133", label: "Way Kanan" },
  { value: "134", label: "Pesawaran" },
  { value: "135", label: "Pringsewu" },
  { value: "136", label: "Mesuji" },
  { value: "137", label: "Tulang Bawang Barat" },
  { value: "138", label: "Pesisir Barat" },
  { value: "139", label: "Kota Bandar Lampung" },
  { value: "140", label: "Kota Metro" },
  { value: "141", label: "Bangka" },
  { value: "142", label: "Belitung" },
  { value: "143", label: "Bangka Selatan" },
  { value: "144", label: "Bangka Tengah" },
  { value: "145", label: "Bangka Barat" },
  { value: "146", label: "Belitung Timur" },
  { value: "147", label: "Kota Pangkal Pinang" },
  { value: "148", label: "Bintan" },
  { value: "149", label: "Karimun" },
  { value: "150", label: "Natuna" },
  { value: "151", label: "Lingga" },
  { value: "152", label: "Kepulauan Anambas" },
  { value: "153", label: "Kota Batam" },
  { value: "154", label: "Kota Tanjung Pinang" },
  { value: "155", label: "Administrasi Kepulauan Seribu" },
  { value: "156", label: "Kota Administrasi Jakarta Pusat" },
  { value: "157", label: "Kota Administrasi Jakarta Utara" },
  { value: "158", label: "Kota Administrasi Jakarta Barat" },
  { value: "159", label: "Kota Administrasi Jakarta Selatan" },
  { value: "160", label: "Kota Administrasi Jakarta Timur" },
  { value: "161", label: "Bogor" },
  { value: "162", label: "Sukabumi" },
  { value: "163", label: "Cianjur" },
  { value: "164", label: "Bandung" },
  { value: "165", label: "Garut" },
  { value: "166", label: "Tasikmalaya" },
  { value: "167", label: "Ciamis" },
  { value: "168", label: "Kuningan" },
  { value: "169", label: "Cirebon" },
  { value: "170", label: "Majalengka" },
  { value: "171", label: "Sumedang" },
  { value: "172", label: "Indramayu" },
  { value: "173", label: "Subang" },
  { value: "174", label: "Purwakarta" },
  { value: "175", label: "Karawang" },
  { value: "176", label: "Bekasi" },
  { value: "177", label: "Bandung Barat" },
  { value: "178", label: "Kota Bogor" },
  { value: "179", label: "Kota Sukabumi" },
  { value: "180", label: "Kota Bandung" },
  { value: "181", label: "Kota Cirebon" },
  { value: "182", label: "Kota Bekasi" },
  { value: "183", label: "Kota Depok" },
  { value: "184", label: "Kota Cimahi" },
  { value: "185", label: "Kota Tasikmalaya" },
  { value: "186", label: "Kota Banjar" },
  { value: "187", label: "Cilacap" },
  { value: "188", label: "Banyumas" },
  { value: "189", label: "Purbalingga" },
  { value: "190", label: "Banjarnegara" },
  { value: "191", label: "Kebumen" },
  { value: "192", label: "Purworejo" },
  { value: "193", label: "Wonosobo" },
  { value: "194", label: "Magelang" },
  { value: "195", label: "Boyolali" },
  { value: "196", label: "Klaten" },
  { value: "197", label: "Sukoharjo" },
  { value: "198", label: "Wonogiri" },
  { value: "199", label: "Karanganyar" },
  { value: "200", label: "Sragen" },
  { value: "201", label: "Grobogan" },
  { value: "202", label: "Blora" },
  { value: "203", label: "Rembang" },
  { value: "204", label: "Pati" },
  { value: "205", label: "Kudus" },
  { value: "206", label: "Jepara" },
  { value: "207", label: "Demak" },
  { value: "208", label: "Kab. Semarang" },
  { value: "209", label: "Temanggung" },
  { value: "210", label: "Kendal" },
  { value: "211", label: "Batang" },
  { value: "212", label: "Pekalongan" },
  { value: "213", label: "Pemalang" },
  { value: "214", label: "Tegal" },
  { value: "215", label: "Brebes" },
  { value: "216", label: "Kota Magelang" },
  { value: "217", label: "Kota Surakarta" },
  { value: "218", label: "Kota Salatiga" },
  { value: "219", label: "Kota Semarang" },
  { value: "220", label: "Kota Pekalongan" },
  { value: "221", label: "Kota Tegal" },
  { value: "222", label: "Kulon Progo" },
  { value: "223", label: "Bantul" },
  { value: "224", label: "Gunung Kidul" },
  { value: "225", label: "Sleman" },
  { value: "226", label: "Kota Yogyakarta" },
  { value: "227", label: "Pacitan" },
  { value: "228", label: "Ponorogo" },
  { value: "229", label: "Trenggalek" },
  { value: "230", label: "Tulungagung" },
  { value: "231", label: "Blitar" },
  { value: "232", label: "Kediri" },
  { value: "233", label: "Malang" },
  { value: "234", label: "Lumajang" },
  { value: "235", label: "Jember" },
  { value: "236", label: "Banyuwangi" },
  { value: "237", label: "Bondowoso" },
  { value: "238", label: "Situbondo" },
  { value: "239", label: "Probolinggo" },
  { value: "240", label: "Pasuruan" },
  { value: "241", label: "Sidoarjo" },
  { value: "242", label: "Mojokerto" },
  { value: "243", label: "Jombang" },
  { value: "244", label: "Nganjuk" },
  { value: "245", label: "Madiun" },
  { value: "246", label: "Magetan" },
  { value: "247", label: "Ngawi" },
  { value: "248", label: "Bojonegoro" },
  { value: "249", label: "Tuban" },
  { value: "250", label: "Lamongan" },
  { value: "251", label: "Gresik" },
  { value: "252", label: "Bangkalan" },
  { value: "253", label: "Sampang" },
  { value: "254", label: "Pamekasan" },
  { value: "255", label: "Sumenep" },
  { value: "256", label: "Kota Kediri" },
  { value: "257", label: "Kota Blitar" },
  { value: "258", label: "Kota Malang" },
  { value: "259", label: "Kota Probolinggo" },
  { value: "260", label: "Kota Pasuruan" },
  { value: "261", label: "Kota Mojokerto" },
  { value: "262", label: "Kota Madiun" },
  { value: "263", label: "Kota Surabaya" },
  { value: "264", label: "Kota Batu" },
  { value: "265", label: "Pandeglang" },
  { value: "266", label: "Lebak" },
  { value: "267", label: "Tangerang" },
  { value: "268", label: "Serang" },
  { value: "269", label: "Kota Tangerang" },
  { value: "270", label: "Kota Cilegon" },
  { value: "271", label: "Kota Serang" },
  { value: "272", label: "Kota Tangerang Selatan" },
  { value: "273", label: "Jembrana" },
  { value: "274", label: "Tabanan" },
  { value: "275", label: "Badung" },
  { value: "276", label: "Gianyar" },
  { value: "277", label: "Klungkung" },
  { value: "278", label: "Bangli" },
  { value: "279", label: "Karangasem" },
  { value: "280", label: "Buleleng" },
  { value: "281", label: "Kota Denpasar" },
  { value: "282", label: "Lombok Barat" },
  { value: "283", label: "Lombok Tengah" },
  { value: "284", label: "Lombok Timur" },
  { value: "285", label: "Sumbawa" },
  { value: "286", label: "Dompu" },
  { value: "287", label: "Bima" },
  { value: "288", label: "Sumbawa Barat" },
  { value: "289", label: "Lombok Utara" },
  { value: "290", label: "Kota Mataram" },
  { value: "291", label: "Kota Bima" },
  { value: "292", label: "Kupang" },
  { value: "293", label: "Timor Tengah Selatan" },
  { value: "294", label: "Timor Tengah Utara" },
  { value: "295", label: "Belu" },
  { value: "296", label: "Alor" },
  { value: "297", label: "Flores Timur" },
  { value: "298", label: "Sikka" },
  { value: "299", label: "Ende" },
  { value: "300", label: "Ngada" },
  { value: "301", label: "Manggarai" },
  { value: "302", label: "Sumba Timur" },
  { value: "303", label: "Sumba Barat" },
  { value: "304", label: "Lembata" },
  { value: "305", label: "Rote Ndao" },
  { value: "306", label: "Manggarai Barat" },
  { value: "307", label: "Nagekeo" },
  { value: "308", label: "Sumba Tengah" },
  { value: "309", label: "Sumba Barat Daya" },
  { value: "310", label: "Manggarai Timur" },
  { value: "311", label: "Sabu Raijua" },
  { value: "312", label: "Kota Kupang" },
  { value: "313", label: "Sambas" },
  { value: "314", label: "Mempawah" },
  { value: "315", label: "Sanggau" },
  { value: "316", label: "Ketapang" },
  { value: "317", label: "Sintang" },
  { value: "318", label: "Kapuas Hulu" },
  { value: "319", label: "Bengkayang" },
  { value: "320", label: "Landak" },
  { value: "321", label: "Sekadau" },
  { value: "322", label: "Melawi" },
  { value: "323", label: "Kayong Utara" },
  { value: "324", label: "Kubu Raya" },
  { value: "325", label: "Kota Pontianak" },
  { value: "326", label: "Kota Singkawang" },
  { value: "327", label: "Kotawaringin Barat" },
  { value: "328", label: "Kotawaringin Timur" },
  { value: "329", label: "Kapuas" },
  { value: "330", label: "Barito Selatan" },
  { value: "331", label: "Barito Utara" },
  { value: "332", label: "Katingan" },
  { value: "333", label: "Seruyan" },
  { value: "334", label: "Sukamara" },
  { value: "335", label: "Lamandau" },
  { value: "336", label: "Gunung Mas" },
  { value: "337", label: "Pulang Pisau" },
  { value: "338", label: "Murung Raya" },
  { value: "339", label: "Barito Timur" },
  { value: "340", label: "Kota Palangka Raya" },
  { value: "341", label: "Tanah Laut" },
  { value: "342", label: "Kotabaru" },
  { value: "343", label: "Banjar" },
  { value: "344", label: "Barito Kuala" },
  { value: "345", label: "Tapin" },
  { value: "346", label: "Hulu Sungai Selatan" },
  { value: "347", label: "Hulu Sungai Tengah" },
  { value: "348", label: "Hulu Sungai Utara" },
  { value: "349", label: "Tabalong" },
  { value: "350", label: "Tanah Bumbu" },
  { value: "351", label: "Balangan" },
  { value: "352", label: "Kota Banjarmasin" },
  { value: "353", label: "Kota Banjarbaru" },
  { value: "354", label: "Paser" },
  { value: "355", label: "Kutai Kartanegara" },
  { value: "356", label: "Berau" },
  { value: "357", label: "Kutai Barat" },
  { value: "358", label: "Kutai Timur" },
  { value: "359", label: "Penajam Paser Utara" },
  { value: "360", label: "Mahakam Ulu" },
  { value: "361", label: "Kota Balikpapan" },
  { value: "362", label: "Kota Samarinda" },
  { value: "363", label: "Kota Bontang" },
  { value: "364", label: "Bulungan" },
  { value: "365", label: "Malinau" },
  { value: "366", label: "Nunukan" },
  { value: "367", label: "Tana Tidung" },
  { value: "368", label: "Kota Tarakan" },
  { value: "369", label: "Bolaang Mongondow" },
  { value: "370", label: "Minahasa" },
  { value: "371", label: "Kepulauan Sangihe" },
  { value: "372", label: "Kepulauan Talaud" },
  { value: "373", label: "Minahasa Selatan" },
  { value: "374", label: "Minahasa Utara" },
  { value: "375", label: "Minahasa Tenggara" },
  { value: "376", label: "Bolaang Mongondow Utara" },
  { value: "377", label: "Kepulauan Siau Tagulandang Biaro" },
  { value: "378", label: "Bolaang Mongondow Timur" },
  { value: "379", label: "Bolaang Mongondow Selatan" },
  { value: "380", label: "Kota Manado" },
  { value: "381", label: "Kota Bitung" },
  { value: "382", label: "Kota Tomohon" },
  { value: "383", label: "Kota Kotamobagu" },
  { value: "384", label: "Banggai" },
  { value: "385", label: "Poso" },
  { value: "386", label: "Donggala" },
  { value: "387", label: "Toli-Toli" },
  { value: "388", label: "Buol" },
  { value: "389", label: "Morowali" },
  { value: "390", label: "Banggai Kepulauan" },
  { value: "391", label: "Parigi Moutong" },
  { value: "392", label: "Tojo Una-Una" },
  { value: "393", label: "Sigi" },
  { value: "394", label: "Banggai Laut" },
  { value: "395", label: "Morowali Utara" },
  { value: "396", label: "Kota Palu" },
  { value: "397", label: "Kepulauan Selayar" },
  { value: "398", label: "Bulukumba" },
  { value: "399", label: "Bantaeng" },
  { value: "400", label: "Jeneponto" },
  { value: "401", label: "Takalar" },
  { value: "402", label: "Gowa" },
  { value: "403", label: "Sinjai" },
  { value: "404", label: "Bone" },
  { value: "405", label: "Maros" },
  { value: "406", label: "Pangkajene dan Kepulauan" },
  { value: "407", label: "Barru" },
  { value: "408", label: "Soppeng" },
  { value: "409", label: "Wajo" },
  { value: "410", label: "Sidenreng Rappang" },
  { value: "411", label: "Pinrang" },
  { value: "412", label: "Enrekang" },
  { value: "413", label: "Luwu" },
  { value: "414", label: "Tana Toraja" },
  { value: "415", label: "Luwu Utara" },
  { value: "416", label: "Luwu Timur" },
  { value: "417", label: "Toraja Utara" },
  { value: "418", label: "Kota Makassar" },
  { value: "419", label: "Kota Parepare" },
  { value: "420", label: "Kota Palopo" },
  { value: "421", label: "Kolaka" },
  { value: "422", label: "Konawe" },
  { value: "423", label: "Muna" },
  { value: "424", label: "Buton" },
  { value: "425", label: "Konawe Selatan" },
  { value: "426", label: "Bombana" },
  { value: "427", label: "Wakatobi" },
  { value: "428", label: "Kolaka Utara" },
  { value: "429", label: "Konawe Utara" },
  { value: "430", label: "Buton Utara" },
  { value: "431", label: "Kolaka Timur" },
  { value: "432", label: "Konawe Kepulauan" },
  { value: "433", label: "Muna Barat" },
  { value: "434", label: "Buton Tengah" },
  { value: "435", label: "Buton Selatan" },
  { value: "436", label: "Kota Kendari" },
  { value: "437", label: "Kota Bau-Bau" },
  { value: "438", label: "Gorontalo" },
  { value: "439", label: "Boalemo" },
  { value: "440", label: "Bone Bolango" },
  { value: "441", label: "Pohuwato" },
  { value: "442", label: "Gorontalo Utara" },
  { value: "443", label: "Kota Gorontalo" },
  { value: "444", label: "Mamuju Utara" },
  { value: "445", label: "Mamuju" },
  { value: "446", label: "Mamasa" },
  { value: "447", label: "Polewali Mandar" },
  { value: "448", label: "Majene" },
  { value: "449", label: "Mamuju Tengah" },
  { value: "450", label: "Maluku Tengah" },
  { value: "451", label: "Maluku Tenggara" },
  { value: "452", label: "Maluku Tenggara Barat" },
  { value: "453", label: "Buru" },
  { value: "454", label: "Seram Bagian Timur" },
  { value: "455", label: "Seram Bagian Barat" },
  { value: "456", label: "Kepulauan Aru" },
  { value: "457", label: "Maluku Barat Daya" },
  { value: "458", label: "Buru Selatan" },
  { value: "459", label: "Kota Ambon" },
  { value: "460", label: "Kota Tual" },
  { value: "461", label: "Halmahera Barat" },
  { value: "462", label: "Halmahera Tengah" },
  { value: "463", label: "Halmahera Utara" },
  { value: "464", label: "Halmahera Selatan" },
  { value: "465", label: "Kepulauan Sula" },
  { value: "466", label: "Halmahera Timur" },
  { value: "467", label: "Pulau Morotai" },
  { value: "468", label: "Pulau Taliabu" },
  { value: "469", label: "Kota Ternate" },
  { value: "470", label: "Kota Tidore Kepulauan" },
  { value: "471", label: "Merauke" },
  { value: "472", label: "Jayawijaya" },
  { value: "473", label: "Jayapura" },
  { value: "474", label: "Nabire" },
  { value: "475", label: "Kepulauan Yapen" },
  { value: "476", label: "Biak Numfor" },
  { value: "477", label: "Puncak Jaya" },
  { value: "478", label: "Paniai" },
  { value: "479", label: "Mimika" },
  { value: "480", label: "Sarmi" },
  { value: "481", label: "Keerom" },
  { value: "482", label: "Pegunungan Bintang" },
  { value: "483", label: "Yahukimo" },
  { value: "484", label: "Tolikara" },
  { value: "485", label: "Waropen" },
  { value: "486", label: "Boven Digoel" },
  { value: "487", label: "Mappi" },
  { value: "488", label: "Asmat" },
  { value: "489", label: "Supiori" },
  { value: "490", label: "Mamberamo Raya" },
  { value: "491", label: "Mamberamo Tengah" },
  { value: "492", label: "Yalimo" },
  { value: "493", label: "Lanny Jaya" },
  { value: "494", label: "Nduga" },
  { value: "495", label: "Puncak" },
  { value: "496", label: "Dogiyai" },
  { value: "497", label: "Intan Jaya" },
  { value: "498", label: "Deiyai" },
  { value: "499", label: "Kota Jayapura" },
  { value: "500", label: "Sorong" },
  { value: "501", label: "Manokwari" },
  { value: "502", label: "Fakfak" },
  { value: "503", label: "Sorong Selatan" },
  { value: "504", label: "Raja Ampat" },
  { value: "505", label: "Teluk Bintuni" },
  { value: "506", label: "Teluk Wondama" },
  { value: "507", label: "Kaimana" },
  { value: "508", label: "Tambrauw" },
  { value: "509", label: "Maybrat" },
  { value: "510", label: "Manokwari Selatan" },
  { value: "511", label: "Pegunungan Arfak" },
  { value: "512", label: "Kota Sorong" },
];

export const PENDIDIKAN_OPTIONS = [
  { value: "1", label: "SD" },
  { value: "2", label: "SMP" },
  { value: "3", label: "SMA/Sederajat" },
  { value: "4", label: "D1" },
  { value: "5", label: "D2" },
  { value: "6", label: "D3" },
  { value: "7", label: "D4" },
  { value: "8", label: "S1" },
  { value: "9", label: "S2" },
  { value: "10", label: "S3" },
];

export const PEKERJAAN_OPTIONS = [
  { value: "1", label: "Belum/Tidak Bekerja" },
  { value: "2", label: "Mengurus Rumah Tangga" },
  { value: "3", label: "Pelajar/Mahasiswa" },
  { value: "4", label: "Pensiunan" },
  { value: "5", label: "Pegawai Negeri Sipil (PNS)" },
  { value: "6", label: "Tentara Nasional Indonesia (TNI)" },
  { value: "7", label: "Kepolisian RI (POLRI)" },
  { value: "8", label: "Perdagangan" },
  { value: "9", label: "Petani/Pekebun" },
  { value: "10", label: "Peternak" },
  { value: "11", label: "Nelayan/Perikanan" },
  { value: "12", label: "Industri" },
  { value: "13", label: "Konstruksi" },
  { value: "14", label: "Transportasi" },
  { value: "15", label: "Karyawan Swasta" },
  { value: "16", label: "Karyawan BUMN" },
  { value: "17", label: "Karyawan BUMD" },
  { value: "18", label: "Karyawan Honorer" },
  { value: "19", label: "Buruh Harian Lepas" },
  { value: "20", label: "Buruh Tani/Perkebunan" },
  { value: "21", label: "Buruh Nelayan/Perikanan" },
  { value: "22", label: "Buruh Peternakan" },
  { value: "23", label: "Pembantu Rumah Tangga" },
  { value: "24", label: "Tukang Cukur" },
  { value: "25", label: "Tukang Listrik" },
  { value: "26", label: "Tukang Batu" },
  { value: "27", label: "Tukang Kayu" },
  { value: "28", label: "Tukang Sol Sepatu" },
  { value: "29", label: "Tukang Las/Pandai Besi" },
  { value: "30", label: "Tukang Jahit" },
  { value: "31", label: "Tukang Gigi" },
  { value: "32", label: "Penata Rias" },
  { value: "33", label: "Penata Busana" },
  { value: "34", label: "Penata Rambut" },
  { value: "35", label: "Mekanik" },
  { value: "36", label: "Seniman" },
  { value: "37", label: "Tabib" },
  { value: "38", label: "Paraji" },
  { value: "39", label: "Perancang Busana" },
  { value: "40", label: "Penterjemah" },
  { value: "41", label: "Imam Masjid" },
  { value: "42", label: "Pendeta" },
  { value: "43", label: "Pastor" },
  { value: "44", label: "Wartawan" },
  { value: "45", label: "Ustadz/Mubaligh" },
  { value: "46", label: "Juru Masak" },
  { value: "47", label: "Promotor Acara" },
  { value: "48", label: "Anggora DPR-RI" },
  { value: "49", label: "Anggota DPD" },
  { value: "50", label: "Anggota BPK" },
  { value: "51", label: "Presiden" },
  { value: "52", label: "Wakil Presiden" },
  { value: "53", label: "Anggota Mahkamah" },
  { value: "54", label: "Konstitusi" },
  { value: "55", label: "Anggota Kabinet/ Kementrian" },
  { value: "56", label: "Duta Besar" },
  { value: "57", label: "Gubernur" },
  { value: "58", label: "Wakil Gubernur" },
  { value: "59", label: "Bupati" },
  { value: "60", label: "Wakil Bupati" },
  { value: "61", label: "Walikota" },
  { value: "62", label: "Wakil Walikota" },
  { value: "63", label: "Anggota DPRD Provinsi/ Anggota DPRD Kabupaten/Kota" },
  { value: "64", label: "Dosen" },
  { value: "65", label: "Guru" },
  { value: "66", label: "Pilot" },
  { value: "67", label: "Pengacara" },
  { value: "68", label: "Notaris" },
  { value: "69", label: "Arsitek" },
  { value: "70", label: "Akuntan" },
  { value: "71", label: "Konsultan" },
  { value: "72", label: "Dokter" },
  { value: "73", label: "Bidan" },
  { value: "74", label: "Perawat" },
  { value: "75", label: "Apoteker" },
  { value: "76", label: "Psikiater/Psikolog" },
  { value: "77", label: "Penyiar Televisi" },
  { value: "78", label: "Penyiar Radio" },
  { value: "79", label: "Pelaut" },
  { value: "80", label: "Peneliti" },
  { value: "81", label: "Sopir" },
  { value: "82", label: "Pialang" },
  { value: "83", label: "Paranormal" },
  { value: "84", label: "Pedagang" },
  { value: "85", label: "Perangkat Desa" },
  { value: "86", label: "Kepala Desa" },
  { value: "87", label: "Biarawati" },
  { value: "88", label: "Wiraswasta" },
  { value: "89", label: "Lainnya" },
];